import type { IraQuestion } from '../tprm/iraCatalog';
import { IRA_QUESTIONS, splitValues } from '../tprm/iraCatalog';
import { VendorTier } from '@prisma/client';

type OverlayAnswer = { questionKey: string; response?: string | null };

export const INSURANCE_IRA_QUESTIONS: IraQuestion[] = [
    { key: 'ins1', part: 'B', question: 'Does the provider perform a regulated insurance function?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins2', part: 'B', question: 'Does the provider have claims authority?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins3', part: 'B', question: 'Does the provider influence underwriting?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins4', part: 'B', question: 'Does it influence pricing?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins5', part: 'B', question: 'Does it process policyholder information?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins6', part: 'B', question: 'Does it process health or sensitive information?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins7', part: 'B', question: 'Does it handle premiums or customer funds?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins8', part: 'B', question: 'Does it interact directly with policyholders?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins9', part: 'B', question: 'Could failure stop claims processing?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins10', part: 'B', question: 'Could failure stop policy issuance or renewal?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins11', part: 'B', question: 'Does it provide predictive or AI models?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins12', part: 'B', question: 'Does it provide underwriting or claims data?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins13', part: 'B', question: 'Does it subcontract material insurance services?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
    { key: 'ins14', part: 'B', question: 'Does it require an insurance license or authorization?', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'dont_know', label: "Don't know" }] },
];

export const INSURANCE_IRA_METADATA = [
    { id: 'ins1', question: 'Does the provider perform a regulated insurance function?', businessMeaning: 'Whether the vendor performs a regulated insurance function.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Business requester who knows the intended service. Legal conclusions are not required.', packTrigger: 'insurance-core', possibleFloor: 'HIGH', possibleHumanReview: 'Yes — confirm the function against the recorded organization type.', countryVariation: 'Nigeria/US licensing context if recorded.', orgTypeVariation: 'Applies to all insurance organization types.', evidenceRationale: 'Service description or statement of work. Do not invent a license.', dontKnow: 'No floor. Unknown is not Yes.' },
    { id: 'ins2', question: 'Does the provider have claims authority?', businessMeaning: 'Delegated claims settlement or adjustment authority.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Claims or operations owner.', packTrigger: 'claims-operations', possibleFloor: 'HIGH', possibleHumanReview: 'Yes — confirm limits on the delegated-authority record.', countryVariation: 'Nigerian loss-adjuster licensing is separate from this question.', orgTypeVariation: 'More material for insurers and TPAs.', evidenceRationale: 'Delegated authority agreement if one exists.', dontKnow: 'No floor.' },
    { id: 'ins3', question: 'Does the provider influence underwriting?', businessMeaning: 'Influence over underwriting decisions.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Underwriting owner.', packTrigger: 'underwriting-pricing', possibleFloor: 'HIGH', possibleHumanReview: 'Yes if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'Insurer/MGA/MGU more than brokers.', evidenceRationale: 'Underwriting guideline or model-use record.', dontKnow: 'No floor.' },
    { id: 'ins4', question: 'Does it influence pricing?', businessMeaning: 'Influence over pricing.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Pricing or actuarial owner.', packTrigger: 'underwriting-pricing', possibleFloor: 'HIGH', possibleHumanReview: 'Yes if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'Insurer/MGA/MGU.', evidenceRationale: 'Pricing guideline or model-use record.', dontKnow: 'No floor.' },
    { id: 'ins5', question: 'Does it process policyholder information?', businessMeaning: 'Policyholder personal data processing.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Privacy or operations owner.', packTrigger: 'privacy', possibleFloor: 'none', possibleHumanReview: 'Privacy review if Yes. Not a lawfulness finding.', countryVariation: 'NDPA/NY overlay applied only via packs.', orgTypeVariation: 'All types that handle customer data.', evidenceRationale: 'Existing Privacy activity record.', dontKnow: 'No floor. Do not invent a privacy finding.' },
    { id: 'ins6', question: 'Does it process health or sensitive information?', businessMeaning: 'Health or other sensitive insurance data.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Privacy owner.', packTrigger: 'health-sensitive-data', possibleFloor: 'CRITICAL', possibleHumanReview: 'Required if Yes.', countryVariation: 'Confirm local health-data rules separately.', orgTypeVariation: 'Life/health more than P&C.', evidenceRationale: 'Privacy activity + health-handling evidence.', dontKnow: 'No floor.' },
    { id: 'ins7', question: 'Does it handle premiums or customer funds?', businessMeaning: 'Premium or customer-fund handling.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Finance or broker operations owner.', packTrigger: 'premium-payments', possibleFloor: 'CRITICAL', possibleHumanReview: 'Required if Yes.', countryVariation: 'Do not invent remittance thresholds.', orgTypeVariation: 'Brokers and payment vendors.', evidenceRationale: 'Service description. Amounts are not invented.', dontKnow: 'No floor.' },
    { id: 'ins8', question: 'Does it interact directly with policyholders?', businessMeaning: 'Direct policyholder interaction.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Customer-operations owner.', packTrigger: 'market-conduct', possibleFloor: 'none', possibleHumanReview: 'Conduct review if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'Distribution and claims servicing.', evidenceRationale: 'Market-conduct procedure if recorded.', dontKnow: 'No floor.' },
    { id: 'ins9', question: 'Could failure stop claims processing?', businessMeaning: 'Failure would stop claims processing.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Claims owner.', packTrigger: 'claims-operations', possibleFloor: 'CRITICAL', possibleHumanReview: 'Required if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'Insurer/TPA/adjuster.', evidenceRationale: 'Critical-service / BCP record if present.', dontKnow: 'No floor.' },
    { id: 'ins10', question: 'Could failure stop policy issuance or renewal?', businessMeaning: 'Failure would stop issuance or renewal.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Policy-administration owner.', packTrigger: 'policy-administration', possibleFloor: 'CRITICAL', possibleHumanReview: 'Required if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'Insurer/policy admin.', evidenceRationale: 'Policy-procedure or BCP evidence.', dontKnow: 'No floor.' },
    { id: 'ins11', question: 'Does it provide predictive or AI models?', businessMeaning: 'Provides predictive or AI models.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'AI governance owner.', packTrigger: 'ai-predictive-models', possibleFloor: 'none unless other answers apply', possibleHumanReview: 'Attach InsuranceAiContext on the existing AI record.', countryVariation: 'NAIC AI bulletin is guidance unless adopted.', orgTypeVariation: 'All.', evidenceRationale: 'Existing AI system + model-validation evidence.', dontKnow: 'No floor.' },
    { id: 'ins12', question: 'Does it provide underwriting or claims data?', businessMeaning: 'Provides underwriting or claims data.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Data or underwriting owner.', packTrigger: 'external-data-providers', possibleFloor: 'none', possibleHumanReview: 'Yes if consumer-impacting.', countryVariation: 'None invented.', orgTypeVariation: 'All.', evidenceRationale: 'External-data record on the vendor.', dontKnow: 'No floor.' },
    { id: 'ins13', question: 'Does it subcontract material insurance services?', businessMeaning: 'Subcontracts material insurance services.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Vendor owner.', packTrigger: 'regulatory-outsourcing', possibleFloor: 'none', possibleHumanReview: 'Fourth-party review if Yes.', countryVariation: 'None invented.', orgTypeVariation: 'All.', evidenceRationale: 'Subcontractor disclosure on the vendor record.', dontKnow: 'No floor.' },
    { id: 'ins14', question: 'Does it require an insurance license or authorization?', businessMeaning: 'An insurance license or authorization is required for the service.', options: ['yes', 'no', 'dont_know'], requesterQualification: 'Compliance owner. Not a legal determination by the requester.', packTrigger: 'insurance-core', possibleFloor: 'HIGH', possibleHumanReview: 'Required if Yes. Recorded license ≠ verified license.', countryVariation: 'Nigeria NAICOM vs US state DOI.', orgTypeVariation: 'Varies by activity.', evidenceRationale: 'Customer-recorded license metadata. Supreme has not verified an official registry unless marked external-source-verified.', dontKnow: 'No floor. Do not fabricate a license finding.' },
] as const;

export function iraQuestionsForEdition(insuranceActive: boolean): IraQuestion[] {
    return insuranceActive ? [...IRA_QUESTIONS, ...INSURANCE_IRA_QUESTIONS] : IRA_QUESTIONS;
}

function yes(answers: OverlayAnswer[], key: string) {
    return splitValues(answers.find((row) => row.questionKey === key)?.response).includes('yes');
}

export function insuranceIraFloors(answers: OverlayAnswer[]) {
    const present = answers.some((row) => String(row.questionKey).startsWith('ins'));
    if (!present) return [];
    return [
        { code: 'ins-regulated-function', label: 'Regulated insurance function', tier: VendorTier.HIGH, applies: yes(answers, 'ins1'), rationale: 'Insurance overlay: regulated function raises the floor. Baseline scoring is unchanged.' },
        { code: 'ins-claims-authority', label: 'Claims authority', tier: VendorTier.HIGH, applies: yes(answers, 'ins2'), rationale: 'Insurance overlay: claims authority.' },
        { code: 'ins-underwriting', label: 'Underwriting influence', tier: VendorTier.HIGH, applies: yes(answers, 'ins3'), rationale: 'Insurance overlay: underwriting influence.' },
        { code: 'ins-pricing', label: 'Pricing influence', tier: VendorTier.HIGH, applies: yes(answers, 'ins4'), rationale: 'Insurance overlay: pricing influence.' },
        { code: 'ins-health', label: 'Health or sensitive insurance data', tier: VendorTier.CRITICAL, applies: yes(answers, 'ins6'), rationale: 'Insurance overlay: sensitive policyholder health data.' },
        { code: 'ins-funds', label: 'Premiums or customer funds', tier: VendorTier.CRITICAL, applies: yes(answers, 'ins7'), rationale: 'Insurance overlay: customer funds.' },
        { code: 'ins-stop-claims', label: 'Failure stops claims', tier: VendorTier.CRITICAL, applies: yes(answers, 'ins9'), rationale: 'Insurance overlay: claims-processing criticality.' },
        { code: 'ins-stop-issuance', label: 'Failure stops issuance or renewal', tier: VendorTier.CRITICAL, applies: yes(answers, 'ins10'), rationale: 'Insurance overlay: policy issuance criticality.' },
        { code: 'ins-license', label: 'Insurance license or authorization required', tier: VendorTier.HIGH, applies: yes(answers, 'ins14'), rationale: 'Insurance overlay: licensing dependency.' },
    ];
}
